# Generated by Django 2.1.7 on 2019-04-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='fixtures/no-image.jpeg', null=True, upload_to='images/'),
        ),
    ]
