# Generated by Django 2.1.7 on 2019-04-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='no-image.jpeg', null=True, upload_to='avatars/'),
        ),
    ]
