# Generated by Django 2.1.7 on 2019-04-02 12:31

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190401_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='no-image.jpeg', null=True, upload_to='avatars/', validators=[users.models.avatar_size]),
        ),
    ]
