# Generated by Django 2.1.7 on 2019-04-15 10:52

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190402_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='no-image.png', null=True, upload_to='avatars/', validators=[users.models.avatar_size]),
        ),
    ]
