# Generated by Django 2.1.7 on 2019-04-10 10:24

from django.db import migrations, models
import qa.models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20190402_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='best_answer',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name=qa.models.Question),
        ),
    ]
