# Generated by Django 2.1.7 on 2019-04-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_answer_best_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='best_answer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
