# Generated by Django 2.1.7 on 2019-04-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_auto_20190410_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
        migrations.AddField(
            model_name='question',
            name='edited_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
