# Generated by Django 2.1.7 on 2019-04-15 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0008_auto_20190415_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
